### ISSUE TITLE
silluq not recognized as an accent?

### ISSUE THREAD

**Issue by bdenckla** [charlesLoder/havarotjs#164]
When I entered "לַֽיהֹוָֽה׃" I was surprised to get the suggestion to include accents:

![image](https://github.com/charlesLoder/havarotjs/assets/941315/288ce6b9-7e93-48e8-a6a4-efffca9815f3)

I thought that by including the _sof pasuq_ mark I would have given it enough informatio to realize that at least one of those two Unicode METEG code points represented _silluq_ rather than _gaʿya_. There is a separate, haunting challenge, which is to figure out which one is the _silluq_ and which one is the _gaʿya_ but I think only perhaps one in perhaps 10,000 times will it be wrong to just assume that the last one is the _silluq_.

**Comment by charlesLoder** [comment]
Closing this issue and recreating it on the [web app repo](https://github.com/charlesLoder/hebrewTransliteration/issues/83).

> There is a separate, haunting challenge, which is to figure out which one is the silluq and which one is the gaʿya but I think only perhaps one in perhaps 10,000 times will it be wrong to just assume that the last one is the silluq.

In this package, I define a silluq in `Cluster.hasSilluq` by checking if the next `Cluster` is a sof pasuq; it may not be 100% correct, but like you indicated, it is almost always correct.

https://github.com/charlesLoder/havarotjs/blob/306ed6f17ca6c2414b569a7e653adaccda9204de/src/cluster.ts#L345-L362
