### ISSUE TITLE
Failed to check validity of charMap types during Next.js 14.1.0 build

### ISSUE THREAD

**Issue by skosonen** [charlesLoder/havarotjs#187]
Version 0.24.1
Hebrew-transliteration library depends on this.
Linked issue: https://github.com/charlesLoder/hebrew-transliteration/issues/97
```
   Linting and checking validity of types  ..Failed to compile.

./node_modules/havarotjs/dist/types/utils/charMap.d.ts:123:5
Type error: Property or signature expected.

  121 |     readonly "\u05C4": "UPPER_DOT";
  122 |     readonly "\u05C5": "LOWER_DOT";
> 123 |     readonly ׯ: "YOD_TRIANGLE";
      |     ^
  124 |     readonly װ: "DOUBLE_VAV";
  125 |     readonly ױ: "VAV_YOD";
  126 |     readonly ײ: "DOUBLE_YOD";
```

**Comment by charlesLoder** [comment]
@skosonen

That's very strange…

Here's a very basic example that seems to be working — https://stackblitz.com/edit/stackblitz-starters-tz361c?file=app%2Fpage.tsx

Just some extra questions:
- Are you using the Yod Triangle character in your transliteration?
- What version of TS are you using? My example defaulted to `5.7.2`

**Comment by skosonen** [comment]
Thanks for checking this, happy to help getting this fixed!

> Are you using the Yod Triangle character in your transliteration?
No.

> What version of TS are you using? My example defaulted to 5.7.2
5.3.2

**Comment by charlesLoder** [comment]
Can you give an example of how it's being used? Does the stackblitz container get to the gist of it?

Is the Next and TS versions match, maybe it's an OS issue. Is this just happening locally, in deployment, or both?

**Comment by skosonen** [comment]
When I downloaded your example stackblitz code on my Mac, and run `npm install` + `npm run build`, I got the same issue:

```
$ npm run build

> stackblitz-starters-tz361c@0.1.0 build
> next build

   ▲ Next.js 14.1.0

   Creating an optimized production build ...
(node:57163) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:57190) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
 ✓ Compiled successfully
   Linting and checking validity of types  ..Failed to compile.

./node_modules/havarotjs/dist/types/utils/charMap.d.ts:123:5
Type error: Property or signature expected.

  121 |     readonly "\u05C4": "UPPER_DOT";
  122 |     readonly "\u05C5": "LOWER_DOT";
> 123 |     readonly ׯ: "YOD_TRIANGLE";
      |     ^
  124 |     readonly װ: "DOUBLE_VAV";
  125 |     readonly ױ: "VAV_YOD";
  126 |     readonly ײ: "DOUBLE_YOD";
  ```

**Comment by charlesLoder** [comment]
Ok, so this is really interesting.

The error only occurs on `build` not `dev`, so it's only happening during type checking.

Even though in the source the key is escaped like this:

https://github.com/charlesLoder/havarotjs/blob/e8c178f33df3a004ea5f8096d29d8fbb547aed3b/src/utils/charMap.ts#L262

It gets compiled to the actual unescaped character — ׯ

Even though this should be valid, TS doesn't like it and throws an error similar to if you try to use a [key with a hyphen](https://bobbyhadz.com/blog/typescript-property-or-signature-expected), e.g.:

```
interface Employee {
  // ⛔️ Error: Property or signature expected.ts(1131)
  first-name: string;
}
```

I'm not sure why/how it gets unescaped.

In your `node_modules/havarotjs/dist/types/utils/charMap.d.ts`, you can change it to this:

```diff
- readonly ׯ: "YOD_TRIANGLE"; 
+ readonly "\u05EF": "YOD_TRIANGLE";
```

To automate it, you can use [`patch-package`](https://www.npmjs.com/package/patch-package).

I think this may be a Typescript bug…

**Comment by skosonen** [comment]
Yes, I also investigated this and came to a same conclusion. Typescript should not complain about these changes that it does automatically. Another option would be to have some kind of setting to disable this unescaping - currently there is none.

Thanks for that patch-package tip, I can try that.

**Comment by charlesLoder** [comment]
@skosonen 

Ok, I think figured it out. If you can, add

```
"target": "ES2020",
```

to the `tsconfig`, that will fix the errors — at least it did locally for me; while testing on Stackblitz I got a more arcane error

**Comment by skosonen** [comment]
Thanks, this seems to fix the issue!
(I might still want to keep the es5 and the old version of the library to be able to support the older browsers though)
