### ISSUE TITLE
Remove Reduce

### ISSUE THREAD

**Issue by charlesLoder** [charlesLoder/havarotjs#49]
Remove `reduce()` (slow), and clean up

https://github.com/charlesLoder/havarotjs/blob/6ca463a8f61a635a38395dea6b0dcc9a8181761a/src/utils/qametsQatan.ts#L86-L92

To something like

```ts
const sequenceSnippets = (arr: string[]) => { 
   return arr.map((snippet) => (sequence(snippet.normalize("NFKD")).flat().join(""));
 }; 
```

**Comment by ryuusama09** [comment]
I would like to do this @charlesLoder

**Comment by charlesLoder** [comment]
> I would like to do this @charlesLoder

Thanks!
